import java.io.File;
import java.util.Date;
import java.util.List;

public interface Organizable {

    //create a new raffle with autogenerated raffle id
    public void createRaffle();
    //maybe raffle can have a variable to store the username of the organizer?
    // also since we need to create a raffle, so we also need to implement raffle at this stage?

    //add rules to the specific raffle id
    public String addRaffleRules(int raffleID, File rulesDescriptionFile);
    //we'll need specific format for the txt file
    //What should include in the rules?
    //Will we be able to change rules afterward?

    //change the end date of the raffle
    public void changeRaffleEndDate(Date newEndDate);

    //declare the raffle prizes
    public void declarePrizes(int raffleID, String rafflePrizes);

    //declare the number of winners of the raffle
    public void declareNumWinners(int raffleID, int numWinners);
    //maybe we can merge the methods declarePrizes() and declareNumWinners() into either
    // createRaffle() or addRaffleRules()?

    //draws and return the winner(s) of a Raffle and notifies the winning participant objects
    public User generateAndNotifyWinner(List<User> participantList);
}
